import pandas as pd
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))

from utils.db_engine import db_engine

def get_store_revenue() -> pd.DataFrame | None:
    """
    Fetch total revenue generated by each store from the database.

    Returns:
        pd.DataFrame | None: DataFrame of store revenue sorted by total revenue,
                             or None if query fails.
    """
    try:
        engine = db_engine()

        # Locate SQL file
        current_dir = Path(__file__).parent
        sql_file_path = current_dir.parent / "sql" / "store_metrics_query.sql"

        if not sql_file_path.exists():
            print(f"Error: SQL file not found at {sql_file_path}")
            return None

        # Read query from file
        query = sql_file_path.read_text()

        # Execute query
        df = pd.read_sql_query(query, engine)

        if df.empty:
            print("Warning: Query returned no results.")
        return df

    except Exception as e:
        print(f"Error executing store revenue query: {e}")
        return None

if __name__ == "__main__":
    result = get_store_revenue()
    if result is not None:
        print(result.head())
    else:
        print("Failed to retrieve data")